#!/usr/bin/env bash
#
# Copyright 2021 by Daniel Ellard.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: these should go into a common parameter file
#

MUSIC_LIBRARY="$HOME/Music/iTunes/iTunes Music"
M4A_LIB="$HOME/UsbMusic/MP3Cache"

SCRIPTDIR="$(dirname $0)"

IFS=""
find "$MUSIC_LIBRARY" -type f | grep -i m4a$ \
	| while read m4a; do
    echo "NEXT [$m4a]"


    mp3=$(echo "$m4a" \
	    | sed -e "s|^$MUSIC_LIBRARY|$M4A_LIB|" \
	    | sed -e 's/\.[^.]*$//' -e s'/$/.mp3/')
    echo "TO [$mp3]"

    target_dir=$(dirname "$mp3")
    if [ ! -d "$target_dir" ]; then
	mkdir -p "$target_dir"
    fi

    "$SCRIPTDIR"/convert-to-mp3 "$m4a" "$mp3"
done
