#!/usr/bin/env bash
#
# Copyright 2021 by Daniel Ellard.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $# -ne 2 ]; then
    echo "ERROR: usage $0 INFILE OUTFILE"
    exit 1
fi

INFILE="$1"
OUTFILE="$2"
OUTDIR=$(dirname "$OUTFILE")

# If the OUTFILE already exists, then don't do anything
#
if [ -f "$OUTFILE" ]; then
    echo "INFO: $0 output file [$OUTFILE] already exists"
    exit 0
fi

if [ ! -e "$INFILE" ]; then
    echo "ERROR: $0 input file [$INFILE] does not exist"
    exit 1
elif [ ! -f "$INFILE" ]; then
    echo "ERROR: $0 input file [$INFILE] is not a regular file"
    exit 1
elif [ ! -r "$INFILE" ]; then
    echo "ERROR: $0 input file [$INFILE] cannot be read"
    exit 1
fi

if [ ! -e "$OUTDIR" ]; then
    echo "ERROR: $0 output directory [$OUTDIR] does not exist"
    exit 1
elif [ ! -d "$OUTDIR" ]; then
    echo "ERROR: $0 output directory [$OUTDIR] is not a directory"
    exit 1
elif [ ! -w "$OUTDIR" ]; then
    echo "ERROR: $0 output directory [$OUTDIR] is not writable"
    exit 1
fi

case "$INFILE" in
    *.mp3)
	echo "Copying [$INFILE]"
	cp "$INFILE" "$OUTFILE"
	if [ $? -ne 0 ]; then
	    echo "ERROR: $0 failure in cp"
	    exit 1
	fi
	;;
    *)
	echo "Converting [$INFILE]"
	ffmpeg -i "$INFILE" \
		-hide_banner -loglevel error -nostats \
		-c:v copy -c:a libmp3lame -q:a 0 "$OUTFILE" < /dev/null
	if [ $? -ne 0 ]; then
	    echo "ERROR: $0 failure in ffmpeg"
	    exit 1
	fi
	;;
esac

chmod 444 "$OUTFILE"
exit 0
